### ISSUE TITLE
Readme instructions for creating the Azure app are no longer valid

### ISSUE THREAD

**Issue by glennblock** [microsoftgraph/nodejs-webhooks-rest-sample#14]
In the readme are the following instructions:

-------
* An app registered in Microsoft Azure. You can use the [Office 365 app registration tool](http://dev.office.com/app-registration). It simplifies app registration. Use the following parameters:

|     Parameter   |              Value             |
|----------------:|:-------------------------------|
|        App type | Web App                        |
|     Sign on URL | http://localhost:3000          |
|    Redirect URI | http://localhost:3000/callback |
| App permissions | Mail.Read                      |
  
  Copy and store the **Client ID** and **Client Secret** values.
--------
Following the link (http://dev.office.com/app-registration) redirects to Azure AD App Registrations, where it is not clear how to proceed or how to get the client ID and secret.

**Comment by glennblock** [comment]
I think I found it looking at newer source: The url for signup should be: https://apps.dev.microsoft.com 

Shouldn't dev.office.com/app-registration redirect to this instead?

**Comment by yinaa** [comment]
Link in the readme is updated.
