### ISSUE TITLE
Hosting the sample on Azure

### ISSUE THREAD

**Issue by Ajaldin** [microsoftgraph/nodejs-webhooks-rest-sample#172]
Hi,
I deployed the app to the cloud using Azure App Services, I properly updated the parameters:

Parameter | Value
App type | Web App
Sign on URL | https://cloud_service_URL>
Redirect URI | https://cloud_service_URL>/callback

I also updated the values in the file constants.js

redirectUri: 'https://cloud_service_URL>/callback'
notificationUrl: 'https://cloud_service_URL>/listen'

But I'm getting this error after trying to login:

![image](https://user-images.githubusercontent.com/38541189/103946184-5902b200-5104-11eb-8de1-eb38b947b487.png)

Any idea to solve this issue?
Thanks

**Comment by Ajaldin** [comment]
Update. 
I moved from a free server to a paid server it seems like the free version doesn't support webhooks. Anyway, I got a new error that I think is related to socket.io.
Any idea about how can I successfully implement socket.io on Azure's App service? or which parameters should I change or add to the sample?
Thanks
![image](https://user-images.githubusercontent.com/38541189/105218499-39678280-5b23-11eb-8c00-2b9ab781304a.png)

**Comment by Jumaodhiss** [comment]
@Ajaldin looks like a socket.io error. Please check if this helps _https://stackoverflow.com/questions/11995406/socket-io-referenceerror-io-is-not-defined_.

**Comment by Ajaldin** [comment]
Hi, I tried all of them, none of them worked for me so far. It's definitely a problem with socket.io, somehow when I run the app that path is not reaching the socket.io resource, therefore, generating errors and not establishing the socket even having got the subscription.
Any idea?

**Comment by Jumaodhiss** [comment]
Sorry @Ajaldin I am not sure why you are facing this issue with socket io. I will go ahead and close this issue from here. Kindly follow this link https://github.com/socketio/socket.io to raise the issue.

**Comment by Ajaldin** [comment]
I had to edit part of the code in order to have this running on Azure App Services.
