### ISSUE TITLE
Update sample to use Azure v2 endpoints

### ISSUE THREAD

**Issue by jasonjoh** [microsoftgraph/nodejs-webhooks-rest-sample#20]

**Comment by baywet** [comment]
Ideally solution: we're using @azure/adal-node
But it's depending on (lined up for FY20Q4)
https://github.com/AzureAD/microsoft-authentication-library-for-js/projects/4
more information
https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/msal-node-base/lib/msal-node

Alternative https://github.com/AzureAD/passport-azure-ad
