### ISSUE TITLE
Error - object Object with object details

### ISSUE THREAD

**Issue by kvinash** [microsoftgraph/nodejs-webhooks-rest-sample#21]
subcription Data null
{ error:
{ code: 'ExtensionError',
message: 'Operation: Create; Exception: [Status Code: NotFound; Reason: Not Found]',
innerError:
{ 'request-id': 'f5af4895-9c74-46fe-a395-aacdff2d61ea',
date: '2018-06-18T19:09:28' } } }

Any response will be appreciated.

**Comment by jasonjoh** [comment]
Not a whole lot of information or context to go on here, such as when you see this error, etc. Not Found would make me think you don't have an Exchange Online mailbox, but I'm really just making guesses.

I'd suggest trying logging in to [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) and see if you can access your inbox messages there.

**Comment by kvinash** [comment]
Yes. I am able to access my inbox messages from graph explorer.
