### ISSUE TITLE
AssertionError [ERR_ASSERTION]

### ISSUE THREAD

**Issue by kyjack** [microsoftgraph/nodejs-webhooks-rest-sample#221]
Hi, I downloaded the sample code and followed the steps created the application, replaced the IDs and secret in constants.js file.
However when I try run, it shows the following error, please refer to attached, which I can't seems to find out what's the root cause of the error.
Hope someone can guide me thought this, thanks in advance.

![image](https://user-images.githubusercontent.com/18575452/110322594-55c96b00-804e-11eb-947c-cff9b34401ab.png)

**Comment by Ajaldin** [comment]
It seems that your MSAL parameters are undefined, double-check on your app registration and your exports.msalConfiguration parameters

**Comment by Jumaodhiss** [comment]
@kyjack please check if you still face this issue and reopen the issue.
