### ISSUE TITLE
Microsoft graph is not pushing any notification even after mail is received in inbox

### ISSUE THREAD

**Issue by Devang142** [microsoftgraph/nodejs-webhooks-rest-sample#24]
I used this sample to create subscription for my inbox and notification URL is also successfully verified. But even after receiving mail into my inbox, graph is not posting any notification to URL. Can someone please assist me? Let me know if more info needed.

**Comment by jasonjoh** [comment]
Not really sure what would cause this if the POST to your app for verification went through, unless you restarted ngrok or something? That would cause the tunnelling URL to change, but the subscription would still be using the old URL.

There's always the possibility that notifications are delayed if something's wrong on the server side (high load, etc.) as well.

**Comment by baywet** [comment]
closing the issue as it's old. Feel free to re-open with more details if you're still having issues
