### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by saraswat40** [microsoftgraph/nodejs-webhooks-rest-sample#26]
Hello,

I am not a nodejs developer so some of the issues I am running into maybe a knowledge issue on my part. My node.js version is 8.10.0 and I am on Ubuntu 18.04. Here is what I have tried:
```
#git clone https://github.com/microsoftgraph/nodejs-webhooks-rest-sample.git
update constants.js
#npm start
```

> microsoft-graph-webhook-nodejs@1.0.0 start /home/saraswat/Downloads/tbd/nodejs-webhooks-rest-sample
> mocha ./tests/confTest.js && nodemon --exec babel-node --presets es2015 ./bin/www

sh: 1: mocha: not found
```
#sudo npm install -g mocha
#npm start
```
sh: 1: nodemon: not found
```
# sudo npm install -g nodemon
#npm start
```
sh: 1: babel-node: not found
```
#sudo npm install -g babel-cli
#npm start
```
/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328
        throw e;
        ^

Error: Couldn't find preset "es2015" relative to directory "/home/xxx/Downloads/tbd/nodejs-webhooks-rest-sample/bin"
```
#sudo npm install -g babel-preset-es2015
#sudo npm install -g babel-preset-env
#npm start
```
[nodemon] starting `babel-node --presets es2015 ./bin/www`
/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328
        throw e;
        ^

Error: Couldn't find preset "es2015" relative to directory "/home/xxx/Downloads/tbd/nodejs-webhooks-rest-sample/bin"
    at /usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19

Please let me know if I am missing something.

**Comment by jasonjoh** [comment]
you should run `npm install` (with no other parameters) from the root of this sample. That will install all dependencies from package.json.

**Comment by saraswat40** [comment]
Thank You!!! I am horrible. I will close this now and go away quietly.
