### ISSUE TITLE
Error Unauthorized

### ISSUE THREAD

**Issue by PerkDev** [microsoftgraph/nodejs-webhooks-rest-sample#28]
In subscriptionConfiguration I changed `changeType` value to `updated`, and `resource` value to `users`. Then tried subscribe and I got error

```
{
  "error": {
    "innerError": {
      "date": "2019-07-03T11:29:39",
      "request-id": "5e7f1fc3-8ef4-4511-b661-35bf7d146cc3"
    },
    "message": "Operation: Create; Exception: [Status Code: Unauthorized; Reason: ]",
    "code": "ExtensionError"
  }
}
```

**Comment by jasonjoh** [comment]
The app's configuration only gives it access to read the logged in user's mail, not to access the organizations user list. You'd need to update the app registration permissions to give it `Users.Read.All` and login with an administrator account.

**Comment by baywet** [comment]
Closing the issue as it's old and has been answered. If you're still running into feel free to open a new issue.
