### ISSUE TITLE
China Office 365 run this sample with error: Access token validation failure. Invalid audience.

### ISSUE THREAD

**Issue by leapyear1969** [microsoftgraph/nodejs-webhooks-rest-sample#289]
i have got the code and don't know why it's not process to get the access token.

and the endpoint already replaced with china end point :https://microsoftgraph.chinacloudapi.cn/

 it shows the error as below, please help me on this, thanks.

[http://localhost:3000/callback?code=0.AAAA29QyyEih30WnFvXYKYW6J0dsHqUKGINIiMbPqUWz20MBAAA.AQABAAIAAADF8uhbdqMKTqrrFtoyDhmY_j19lqpK0yArdb2d93hbPyEDlFU_FJrfuvXfwKBiiTba-g7BOW4G2l8qP0fA4rSZoq3nxyglkKU20wZaOSnFQht_OUiUljUzLhZDMplDSwM8tFhcqqrQ1X7MoeCVj8z6Cw8diXW5Ta2aKPCkoOsjI99EiqWVZQEusOdBwXSfxLzirDQf5r3T9OxF-YlS_YtZqNdiMIJhD38ZcCZWPufOH8A57HBH3ZCyRUOmMlNq97_cxbdGAo5x3ij0aNsMKoXbGyjd7C0vjLsHG1rxjrVPd6_ZWAsQT0nahbA8yoZI2VZDoa7wE08hib_at8XX49yLlydtRjeGzY05ebWUrP03f4v8zxB7m2JvMXGv1e5xfPFcKKice6H7spibxFzSa3__7z4bL7KIl1fs3kLI5vOsU3G5icANfZXOajk2dLBjYj1CjEfPbKywOIwXNC7Es3AOXhUBDnczVrJVrJ0GlXBGsLuGCHvzQJeWCEmIle9V5EyN1uCrcMt8h-mHWGpHt1Zcls7ScjXpNlj5m97k36Psfhrldg6Ra8CxsmVQBge5sHoRT7vFKVtyIoKLEsuKRdrfJMNE5vWabRaIpiF4gWZP3DexCNNpoqc6OdgAXFEPIzYgAA&client_info=eyJ1aWQiOiI0ZDI1MmZmOS1lNWExLTQ5NTMtYjUzMC04NTlhNjUyMzMzZDkiLCJ1dGlkIjoiYzgzMmQ0ZGItYTE0OC00NWRmLWE3MTYtZjVkODI5ODViYTI3In0&session_state=935b02c9-197e-4848-9b48-9e70e99df752#](url)
Error: Access token validation failure. Invalid audience.
    at new GraphError (C:\Users\ma.jun\Desktop\nodejs-webhooks-rest-sample-main\node_modules\@microsoft\microsoft-graph-client\src\GraphError.ts:59:3)
    at Function.GraphErrorHandler.constructErrorFromResponse (C:\Users\ma.jun\Desktop\nodejs-webhooks-rest-sample-main\node_modules\@microsoft\microsoft-graph-client\src\GraphErrorHandler.ts:62:18)
    at Function.<anonymous> (C:\Users\ma.jun\Desktop\nodejs-webhooks-rest-sample-main\node_modules\@microsoft\microsoft-graph-client\src\GraphErrorHandler.ts:89:31)
    at step (C:\Users\ma.jun\Desktop\nodejs-webhooks-rest-sample-main\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\Users\ma.jun\Desktop\nodejs-webhooks-rest-sample-main\node_modules\tslib\tslib.js:122:57)
    at C:\Users\ma.jun\Desktop\nodejs-webhooks-rest-sample-main\node_modules\tslib\tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\ma.jun\Desktop\nodejs-webhooks-rest-sample-main\node_modules\tslib\tslib.js:111:16)
    at Function.GraphErrorHandler.getError (C:\Users\ma.jun\Desktop\nodejs-webhooks-rest-sample-main\node_modules\@microsoft\microsoft-graph-client\lib\src\GraphErrorHandler.js:88:24)
    at GraphRequest.<anonymous> (C:\Users\ma.jun\Desktop\nodejs-webhooks-rest-sample-main\node_modules\@microsoft\microsoft-graph-client\src\GraphRequest.ts:386:55)

![error](https://user-images.githubusercontent.com/18607988/121501609-f8103a80-ca11-11eb-8931-e2035bc50d27.png)
![localhost300](https://user-images.githubusercontent.com/18607988/121501921-402f5d00-ca12-11eb-953e-bfcc81d3bcf7.png)

**Comment by baywet** [comment]
Hey @leapyear1969 
Thanks for reaching out.
Have you updated the authority to get the token as well? https://github.com/microsoftgraph/nodejs-webhooks-rest-sample/blob/95a4c2d3e7205744a80a78558ac1cad2fe470457/constants.js#L2

**Comment by leapyear1969** [comment]
> Hey @leapyear1969
> Thanks for reaching out.
> Have you updated the authority to get the token as well?
> 
> https://github.com/microsoftgraph/nodejs-webhooks-rest-sample/blob/95a4c2d3e7205744a80a78558ac1cad2fe470457/constants.js#L2

hello Vincent,

yes, i have updated the authority, i also test in another nodejs program to get the access token successfully via MSAL library.

there is an error in the debug windows, i marked it in the red box.
here is the screenshot:
![authority](https://user-images.githubusercontent.com/18607988/121616099-cc826400-ca94-11eb-81bb-2247d35b18a8.png)

**Comment by leapyear1969** [comment]
hi vincent, 

 I have fixed the "Could not read soucr map" error by configure my npm environment.

but i still can get the : Access token validation failure. Invalid audience. error.

**Comment by baywet** [comment]
Have you also updated this?
https://github.com/microsoftgraph/nodejs-webhooks-rest-sample/blob/95a4c2d3e7205744a80a78558ac1cad2fe470457/routes/auth.js#L84

And here have you added `baseUrl: 'https://microsoftgraph.chinacloudapi.cn/',` ?
https://github.com/microsoftgraph/nodejs-webhooks-rest-sample/blob/95a4c2d3e7205744a80a78558ac1cad2fe470457/helpers/requestHelper.js#L11

**Comment by leapyear1969** [comment]
hello  @baywet 

yes , i did update the url in auth.js . 
`      res.redirect('https://https://login.chinacloudapi.cn/common/oauth2/logout?post_logout_redirect_uri=' + redirectUri);
` 

 i am new to Microsoft Graph api, what should i update in below request?

> And here have you added `baseUrl: 'https://microsoftgraph.chinacloudapi.cn/',` ?
> https://github.com/microsoftgraph/nodejs-webhooks-rest-sample/blob/95a4c2d3e7205744a80a78558ac1cad2fe470457/helpers/requestHelper.js#L11





Besides, according to the error message, i found this document, 

[https://docs.microsoft.com/en-us/graph/webhooks-with-resource-data](url)

i think there is something wrong with the token validation.(though i haven't get a access token)

[https://github.com/microsoftgraph/nodejs-webhooks-rest-sample/blob/95a4c2d3e7205744a80a78558ac1cad2fe470457/helpers/tokenHelper.js](url)

i don't know if there is anything wrong with below function:

```
const client = jkwsClient({
  jwksUri: 'https://login.chinacloudapi.cn/common/discovery/v2.0/keys'
  //jwksUri: 'https://login.microsoftonline.com/common/discovery/v2.0/keys'
});


export function isTokenValid(token, appId, tenantId) {
  return new Promise((resolve) => {
    const options = {
      audience: [appId],
      issuer: [`https://sts.chinacloudapi.cn/c832d4db-a148-45df-a716-f5d82985ba27/`]
      //issuer: [`https://sts.windows.net/${tenantId}/`]
    };
    jwt.verify(token, getKey, options, (err) => {
      if (err) {
        // eslint-disable-next-line no-console
        console.error(err);
        resolve(false);
      } else {
        resolve(true);
      }
    });
  });
}


```

**Comment by baywet** [comment]
```TS
const client = MicrosoftGraph.Client.init({
      authProvider: (done) => {
        done(null, this.accessToken);
      }
    })
```
should look like that

```TS
const client = MicrosoftGraph.Client.init({
      authProvider: (done) => {
        done(null, this.accessToken);
      },
      baseUrl: 'https://microsoftgraph.chinacloudapi.cn/'
    })
```

Can you copy the access token in https://jwt.ms and then copy the decoded value here please? (don't copy the token itself here)

**Comment by leapyear1969** [comment]
hi @baywet 

Thanks so much for your help, I enabled the OpenSSL feature, i can now successfully get the notification. 

`choco install openssl -y`

[https://github.com/microsoftgraph/nodejs-webhooks-rest-sample/blob/main/helpers/certificateHelper.js](url)

Thanks again! :)
