### ISSUE TITLE
Incorrect token persisted for API access

### ISSUE THREAD

**Issue by iambmelt** [microsoftgraph/nodejs-webhooks-rest-sample#4]
Per [this file](https://github.com/OfficeDev/Microsoft-Graph-Nodejs-Webhooks/blob/master/helpers/dbHelper.js#L22)

We should adjust the sample to persist the `refreshToken` instead of the `accessToken`

The `accessToken` is valid for 60 mins whereas the `refreshToken` is valid for 14 days (as of this writing). The `refreshToken` [so long as it is used prior to exp.] can be used to renegotiate a new `accessToken` and `refreshToken`.

With this in mind, we should change _which_ token that this sample persists: it should persist the `refreshToken`.

For an example of how the `refreshToken` can be used to renegotiate access, see [this file](https://github.com/OfficeDev/O365-Nodejs-Microsoft-Graph-Connect/blob/master/authHelper.js#L60)

/cc @jdruid

**Comment by Ricalo** [comment]
The sample just uses the access token to create a subscription after the user signs in. The application just needs the access token a few seconds after the user logs in. Hence the need for some sort of storage of the access token.

Token persistence or refresh flow is not what we're trying to demonstrate in this sample.

Here are the goals of this sample:

* Show how to create a subscription to an event in Office 365.
* Show how to listen to notifications to such events.

So, maybe the storage method (a sqlite database) is deviating you from the real goals of this sample? If that is the case, I'll be happy to discuss a different storage method.

**Comment by iambmelt** [comment]
I think there's value in demonstrating persistence of tokens - if not in this sample, in another perhaps.

That said, if we're going to go through the motions of persisting tokens in this sample, we can work together to see that it demonstrates the recommended pattern; I think we can make some relatively small tweaks and have something that hits all our goals, whatever we decide to make them 👍

**Comment by garethj-msft** [comment]
Agree that it should persist the refresh token, not access.   We don't ever want apps to persist access tokens so we shouldn't have that practice happening in a sample, and token persistence on the whole is material to webhooks design in the delegate case.

**Comment by Ricalo** [comment]
The sample doesn't show how to renew subscriptions. In that scenario the refresh token plays a more significant role.
Persisting a refresh token is a security-sensitive task. Granted, persisting an access token is also sensitive, but the danger is lessened by the token lifespan. Developers must carefully think about persisting a refresh token and not copy a pattern from a sample. A pattern might not be adequate for their particular environments.
I'd be happy to revisit the scope of the sample to include subscription renewal (and refresh token management) or create content (sample or whatever) that shows how to appropriately persist the token. However, we need to involve the right people here. Failing to do so would be irresponsible.

**Comment by DianeD** [comment]
Hi. I noted in our backlog that we need to revisit this question if we do more work on this sample. Closing for now. Thanks
