### ISSUE TITLE
nodejs-webhook: Error 

### ISSUE THREAD

**Issue by girishkumarbk** [microsoftgraph/nodejs-webhooks-rest-sample#8]
Hi,

I'm trying to run webhook sample through ngrok tunnel.  After loging into the microsoft online the app connects to sample app registered but when returns back to localhost, I'm seeing a unexpected token..."SyntaxError: Unexpected token" as shown below.

Express server listening on port 3000
GET / 304 8.723 ms - -
GET /css/fabric.min.css 304 2.541 ms - -
GET /css/fabric.components.min.css 304 1.857 ms - -
GET /signin 302 15.009 ms - 394
POST /listen?validationToken=ZTc4MGRjNDgtM2M3NC00YWRmLWE4YTQtNjFlNzk0MTVkMTVj 200 11.700 ms - 48
undefined:1
{
^

SyntaxError: Unexpected token ﻿
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/Users/girishkb/O365/nodejs_webhooks/nodejs-webhooks-rest-sample/helpers/requestHelper.js:36:23)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

npm ERR! Darwin 13.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! o365-nodejs-webhook@0.0.1 start: `mocha ./tests/confTest.js && node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the o365-nodejs-webhook@0.0.1 start script 'mocha ./tests/confTest.js && node ./bin/www'.
npm ERR! This is most likely a problem with the o365-nodejs-webhook package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha ./tests/confTest.js && node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs o365-nodejs-webhook
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls o365-nodejs-webhook
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/girishkb/O365/nodejs_webhooks/nodejs-webhooks-rest-sample/npm-debug.log

Any idea as to why this unexpected error is thrown ?

Regards,
Girish BK

**Comment by Ricalo** [comment]
Hi @girishkumarbk 

That line should process the error response. It looks like the error is not returned in JSON format. Unfortunately, I can't repro the error. I tried with node v4.6.0 but no luck.

Would you mind adding the following line right before line 36 in helpers/requestHelper.js to inspect the error data?

```
console.log(subscriptionData);
```

This should give us more information.

**Comment by girishkumarbk** [comment]
Hi Recardo,

After putting console log ... this is what is logged on screen as below.
Any idea where am I going wrong ?

Thank You,
/Girish BK


Express server listening on port 3000
GET / 304 4.948 ms - -
GET /css/fabric.min.css 304 1.841 ms - -
GET /css/fabric.components.min.css 304 0.526 ms - -
GET /signin 302 7.019 ms - 394
POST /listen?validationToken=OGIwM2M3OGEtMTYwMC00NTJjLWFmOTQtNzc1OTkyODQwN2Zm 200 2.422 ms - 48
{
  "error": {
    "code": "ExtensionError",
    "message": "An error occurred when creating an entity. Exception: Server Error. Status Code: NotFound, Reason: Not Found",
    "innerError": {
      "request-id": "7f60ca13-3177-4105-8831-498cbef7d4f8",
      "date": "2016-10-19T15:04:15"
    }
  }
}
undefined:1
{
^

SyntaxError: Unexpected token ﻿
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/Users/girishkb/O365/nodejs_webhooks/nodejs-webhooks-rest-sample/helpers/requestHelper.js:37:23)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

npm ERR! Darwin 13.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! o365-nodejs-webhook@0.0.1 start: `mocha ./tests/confTest.js && node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the o365-nodejs-webhook@0.0.1 start script 'mocha ./tests/confTest.js && node ./bin/www'.
npm ERR! This is most likely a problem with the o365-nodejs-webhook package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha ./tests/confTest.js && node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs o365-nodejs-webhook
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls o365-nodejs-webhook
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/girishkb/O365/nodejs_webhooks/nodejs-webhooks-rest-sample/npm-debug.log

**Comment by Ricalo** [comment]
Mmm looks like an error in the service when the sample is trying to create the subscription. Can you confirm that your app registration has the **Send mail as a user** delegated permission?

Also, could you send an email to the account you're using and verify that the message is in the account's inbox?

**Comment by girishkumarbk** [comment]
It looks like you are right!  Actually, I don't have outlook app in my account :)  I'll rerun the app after installing applications on my account.  Will revert back soon if I get through this error...

Thanks

**Comment by Ricalo** [comment]
You probably should follow the principle of least privilege. Your app should only request and access the resources required to do its work.
However, there might be scenarios where the app should access resources even without user consent and that's one of the reasons why admin consent exists.

You should carefully review what permissions your app needs. I'm afraid I can't just say stick to user consent because your app might have a legitimate reason to request for admin consent.

Not very helpful, I know, but this is one of those topics that don't have an easy answer.
